### ISSUE TITLE
Plugin dont refresh permissions of players

### ISSUE THREAD

**Issue by TheNylox** [utarwyn/EnderContainers#107]
**Versions**
Endercontainer version : 2.2.0
Running on Tuinity 1.16.3

Actually everytime a player unlock a new row of enderchest the plugin dont detect it. I need to reload the plugin everytime to make it check the new permissions

**To Reproduce**
Give to a player the permission : endercontainers.slot1.row4
Check if he got the new row
If not , reload the plugin
New row appear

**Expected behavior**
When giving a new permission a player should be aple to use the new row/ec immediatly

**Comment by TheNylox** [comment]
If the player relog the permission get refreshed

**Comment by utarwyn** [comment]
Hello @TheNylox, thank you for your feedback about my plugin.

Indeed, this bug is well-known on the version 2.2.0 of **EnderContainers** I think. Another user has already sent me a feedback about it that you can find it here: #88. The latest development build fixes that problem **(2.2.1-dev)** but may be unstable. If you want you can download it by following [this link](https://ci.utarwyn.fr/job/EnderContainers/lastSuccessfulBuild/).

I hope to release a stable version with the fix soon.
