### ISSUE TITLE
Versions and spigot

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#26]
Why don't release new versions on Spigot?

**Comment by utarwyn** [comment]
I agree, I should release new versions on Spigot.
I just want to fix all errors with threads before releasing it.

I want to be more regular with versions, because since the last year, I have only worked on version 2.2.0, that's not a good work method.

Sorry for that, I will do better in the future :smiley:

**Comment by utarwyn** [comment]
I'm pretty happy with what I have done on the plugin for this version **2.2.0**. So I will release this one as soon as possible (after so much waiting!). I just want to resolve issues #39 and #56 before, then the plugin will be ready to go. :tada:

Is all working fine for you? Or do you want me to work on something else for this version?

**Comment by utarwyn** [comment]
Done, I close this issue. You can find the latest update on Spigot here: https://www.spigotmc.org/resources/endercontainers.4750/update?update=347131
