### ISSUE TITLE
Personalize the item of an enderchest in the menu

### ISSUE THREAD

**Issue by utarwyn** [utarwyn/EnderContainers#32]
I can add a feature for server administrators to personalize the representative item of all enderchests in the main menu. **I already have some ideas of personalization:**
- custom material type
- custom item count
- custom item lore
- new placeholder with the items count in an enderchest

If you have any idea about that, feel free to contribute! 😃

**Comment by pintoso** [comment]
add an option so that %num% also shows like this, this makes it easier to choose and organize items quickly


before:
![image](https://user-images.githubusercontent.com/26844778/101579075-ca8dfa00-39b8-11eb-9e83-1d95bb79fae1.png)
after:
![image](https://user-images.githubusercontent.com/26844778/101578948-c19d2880-39b8-11eb-9fff-603bd699b30b.png)

**Comment by utarwyn** [comment]
@pintoso, I have worked on a new configuration named `numberingEnderchests` to choose if items amount should follows enderchest numbers. But do you have an idea on how to handle enderchest numbers greater than 64?

Actual behavior is:
![image](https://user-images.githubusercontent.com/9255967/128645038-8e922f85-e084-47ef-8ead-8a076102527e.png)
