### ISSUE TITLE
mvn package not work

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#6]
![kepkivagas](https://user-images.githubusercontent.com/8324198/42580729-771f8da0-852b-11e8-9c65-3e91ebffe9fe.PNG)

**Comment by utarwyn** [comment]
Hello @andris155,
I don't think this is due to my plugin, because the error says: "No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?". This seems to be an error with your development environment. Also, I don't have any error when compiling the plugin on my computer.

So, that's very strange, have you other clearer error?
