### ISSUE TITLE
Mini Memory Leak in plugin?

### ISSUE THREAD

**Issue by radek203** [utarwyn/EnderContainers#74]
As in the subject.
![Przechwytywanie](https://user-images.githubusercontent.com/57212337/84315150-86d14980-ab69-11ea-8db8-11d9ae7caddd.PNG)
Maybe it's a mini memory leak?

**Comment by utarwyn** [comment]
I have found that **chests of a player are not removed from the memory when he disconnects looking into a container**. But this should never occurs because a player has to close its inventory to disconnect. I will try to do some advanced tests to check whether the context is deleted each time.

Do you use the command `/ecp open` to open other player chests (even offlines) frequently? Its maybe due to a problem with the offline player chests loading system.

**Comment by radek203** [comment]
So I used /ecp recently

**Comment by utarwyn** [comment]
Do you still have the issue on your server? I have made some tests with multiple players by trying all cases of login / logout and nothing happens (even when using command `/ecp open` on offline players). The plugin context still remain empty when all players are disconnected.

On your screen, there is only two entries in the context map, so is there really a problem? But I agree with you that this map stores 3 629 984 bytes of data, that is a large amount. Maybe chests in memory are quite full?

**Comment by radek203** [comment]
I completely don't know how it arises and when. In recent times, the consumption of the RAM has increased for me and I just dumped the memory

**Comment by radek203** [comment]
@utarwyn Will it be fixed?

**Comment by utarwyn** [comment]
I'm sorry but I don't have any idea why your problem occurs... On my test server I don't have memory issues (I have done a lot of tests). Without more info I'm afraid I can't help you...

**Comment by utarwyn** [comment]
I'm waiting for other people to give a me feedback about that issue. I will release the plugin as this and I will do an update if needed to fix that bug. I hope this does not constraint you too much.
